//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirWebServiceFeminicidio.SR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Verdugo", Namespace="http://intec.edu.do")]
    [System.SerializableAttribute()]
    public partial class Verdugo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        private System.DateTime FechaNacimientoField;
        
        private System.DateTime FechaEventoField;
        
        private int CantidadHijosField;
        
        private int VivoField;
        
        private int PresoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaEvento {
            get {
                return this.FechaEventoField;
            }
            set {
                if ((this.FechaEventoField.Equals(value) != true)) {
                    this.FechaEventoField = value;
                    this.RaisePropertyChanged("FechaEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int CantidadHijos {
            get {
                return this.CantidadHijosField;
            }
            set {
                if ((this.CantidadHijosField.Equals(value) != true)) {
                    this.CantidadHijosField = value;
                    this.RaisePropertyChanged("CantidadHijos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Vivo {
            get {
                return this.VivoField;
            }
            set {
                if ((this.VivoField.Equals(value) != true)) {
                    this.VivoField = value;
                    this.RaisePropertyChanged("Vivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Preso {
            get {
                return this.PresoField;
            }
            set {
                if ((this.PresoField.Equals(value) != true)) {
                    this.PresoField = value;
                    this.RaisePropertyChanged("Preso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Indicio", Namespace="http://intec.edu.do")]
    [System.SerializableAttribute()]
    public partial class Indicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://intec.edu.do")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        private int tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((this.tipoField.Equals(value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intec.edu.do", ConfigurationName="SR.FeminicidiosWebServiceSoap")]
    public interface FeminicidiosWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/HelloWorld", ReplyAction="*")]
        ConsumirWebServiceFeminicidio.SR.HelloWorldResponse HelloWorld(ConsumirWebServiceFeminicidio.SR.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirWebServiceFeminicidio.SR.HelloWorldResponse> HelloWorldAsync(ConsumirWebServiceFeminicidio.SR.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name verdugo from namespace http://intec.edu.do is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RegistrarDatos", ReplyAction="*")]
        ConsumirWebServiceFeminicidio.SR.RegistrarDatosResponse RegistrarDatos(ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RegistrarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirWebServiceFeminicidio.SR.RegistrarDatosResponse> RegistrarDatosAsync(ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://intec.edu.do", Order=0)]
        public ConsumirWebServiceFeminicidio.SR.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumirWebServiceFeminicidio.SR.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://intec.edu.do", Order=0)]
        public ConsumirWebServiceFeminicidio.SR.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumirWebServiceFeminicidio.SR.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarDatos", Namespace="http://intec.edu.do", Order=0)]
        public ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequestBody Body;
        
        public RegistrarDatosRequest() {
        }
        
        public RegistrarDatosRequest(ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class RegistrarDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumirWebServiceFeminicidio.SR.Verdugo verdugo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ConsumirWebServiceFeminicidio.SR.Indicio indicio;
        
        public RegistrarDatosRequestBody() {
        }
        
        public RegistrarDatosRequestBody(ConsumirWebServiceFeminicidio.SR.Verdugo verdugo, ConsumirWebServiceFeminicidio.SR.Indicio indicio) {
            this.verdugo = verdugo;
            this.indicio = indicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarDatosResponse", Namespace="http://intec.edu.do", Order=0)]
        public ConsumirWebServiceFeminicidio.SR.RegistrarDatosResponseBody Body;
        
        public RegistrarDatosResponse() {
        }
        
        public RegistrarDatosResponse(ConsumirWebServiceFeminicidio.SR.RegistrarDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do")]
    public partial class RegistrarDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumirWebServiceFeminicidio.SR.Respuesta RegistrarDatosResult;
        
        public RegistrarDatosResponseBody() {
        }
        
        public RegistrarDatosResponseBody(ConsumirWebServiceFeminicidio.SR.Respuesta RegistrarDatosResult) {
            this.RegistrarDatosResult = RegistrarDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FeminicidiosWebServiceSoapChannel : ConsumirWebServiceFeminicidio.SR.FeminicidiosWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeminicidiosWebServiceSoapClient : System.ServiceModel.ClientBase<ConsumirWebServiceFeminicidio.SR.FeminicidiosWebServiceSoap>, ConsumirWebServiceFeminicidio.SR.FeminicidiosWebServiceSoap {
        
        public FeminicidiosWebServiceSoapClient() {
        }
        
        public FeminicidiosWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeminicidiosWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeminicidiosWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeminicidiosWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirWebServiceFeminicidio.SR.HelloWorldResponse ConsumirWebServiceFeminicidio.SR.FeminicidiosWebServiceSoap.HelloWorld(ConsumirWebServiceFeminicidio.SR.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumirWebServiceFeminicidio.SR.HelloWorldRequest inValue = new ConsumirWebServiceFeminicidio.SR.HelloWorldRequest();
            inValue.Body = new ConsumirWebServiceFeminicidio.SR.HelloWorldRequestBody();
            ConsumirWebServiceFeminicidio.SR.HelloWorldResponse retVal = ((ConsumirWebServiceFeminicidio.SR.FeminicidiosWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirWebServiceFeminicidio.SR.HelloWorldResponse> ConsumirWebServiceFeminicidio.SR.FeminicidiosWebServiceSoap.HelloWorldAsync(ConsumirWebServiceFeminicidio.SR.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirWebServiceFeminicidio.SR.HelloWorldResponse> HelloWorldAsync() {
            ConsumirWebServiceFeminicidio.SR.HelloWorldRequest inValue = new ConsumirWebServiceFeminicidio.SR.HelloWorldRequest();
            inValue.Body = new ConsumirWebServiceFeminicidio.SR.HelloWorldRequestBody();
            return ((ConsumirWebServiceFeminicidio.SR.FeminicidiosWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirWebServiceFeminicidio.SR.RegistrarDatosResponse ConsumirWebServiceFeminicidio.SR.FeminicidiosWebServiceSoap.RegistrarDatos(ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequest request) {
            return base.Channel.RegistrarDatos(request);
        }
        
        public ConsumirWebServiceFeminicidio.SR.Respuesta RegistrarDatos(ConsumirWebServiceFeminicidio.SR.Verdugo verdugo, ConsumirWebServiceFeminicidio.SR.Indicio indicio) {
            ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequest inValue = new ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequest();
            inValue.Body = new ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequestBody();
            inValue.Body.verdugo = verdugo;
            inValue.Body.indicio = indicio;
            ConsumirWebServiceFeminicidio.SR.RegistrarDatosResponse retVal = ((ConsumirWebServiceFeminicidio.SR.FeminicidiosWebServiceSoap)(this)).RegistrarDatos(inValue);
            return retVal.Body.RegistrarDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirWebServiceFeminicidio.SR.RegistrarDatosResponse> ConsumirWebServiceFeminicidio.SR.FeminicidiosWebServiceSoap.RegistrarDatosAsync(ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequest request) {
            return base.Channel.RegistrarDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirWebServiceFeminicidio.SR.RegistrarDatosResponse> RegistrarDatosAsync(ConsumirWebServiceFeminicidio.SR.Verdugo verdugo, ConsumirWebServiceFeminicidio.SR.Indicio indicio) {
            ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequest inValue = new ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequest();
            inValue.Body = new ConsumirWebServiceFeminicidio.SR.RegistrarDatosRequestBody();
            inValue.Body.verdugo = verdugo;
            inValue.Body.indicio = indicio;
            return ((ConsumirWebServiceFeminicidio.SR.FeminicidiosWebServiceSoap)(this)).RegistrarDatosAsync(inValue);
        }
    }
}
