//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirWebServiceTEO5.SR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://intec.edu.do/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://intec.edu.do/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        private int tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((this.tipoField.Equals(value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intec.edu.do/", ConfigurationName="SR.WebServiceTEO6Soap")]
    public interface WebServiceTEO6Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://intec.edu.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/HelloWorld", ReplyAction="*")]
        ConsumirWebServiceTEO5.SR.HelloWorldResponse HelloWorld(ConsumirWebServiceTEO5.SR.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirWebServiceTEO5.SR.HelloWorldResponse> HelloWorldAsync(ConsumirWebServiceTEO5.SR.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/Sumar", ReplyAction="*")]
        int Sumar(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/Sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumarAsync(int num1, int num2);
        
        // CODEGEN: Generating message contract since element name cliente from namespace http://intec.edu.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RegistrarCliente", ReplyAction="*")]
        ConsumirWebServiceTEO5.SR.RegistrarClienteResponse RegistrarCliente(ConsumirWebServiceTEO5.SR.RegistrarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intec.edu.do/RegistrarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirWebServiceTEO5.SR.RegistrarClienteResponse> RegistrarClienteAsync(ConsumirWebServiceTEO5.SR.RegistrarClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://intec.edu.do/", Order=0)]
        public ConsumirWebServiceTEO5.SR.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumirWebServiceTEO5.SR.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://intec.edu.do/", Order=0)]
        public ConsumirWebServiceTEO5.SR.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumirWebServiceTEO5.SR.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarCliente", Namespace="http://intec.edu.do/", Order=0)]
        public ConsumirWebServiceTEO5.SR.RegistrarClienteRequestBody Body;
        
        public RegistrarClienteRequest() {
        }
        
        public RegistrarClienteRequest(ConsumirWebServiceTEO5.SR.RegistrarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do/")]
    public partial class RegistrarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumirWebServiceTEO5.SR.Cliente cliente;
        
        public RegistrarClienteRequestBody() {
        }
        
        public RegistrarClienteRequestBody(ConsumirWebServiceTEO5.SR.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarClienteResponse", Namespace="http://intec.edu.do/", Order=0)]
        public ConsumirWebServiceTEO5.SR.RegistrarClienteResponseBody Body;
        
        public RegistrarClienteResponse() {
        }
        
        public RegistrarClienteResponse(ConsumirWebServiceTEO5.SR.RegistrarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intec.edu.do/")]
    public partial class RegistrarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumirWebServiceTEO5.SR.Respuesta RegistrarClienteResult;
        
        public RegistrarClienteResponseBody() {
        }
        
        public RegistrarClienteResponseBody(ConsumirWebServiceTEO5.SR.Respuesta RegistrarClienteResult) {
            this.RegistrarClienteResult = RegistrarClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTEO6SoapChannel : ConsumirWebServiceTEO5.SR.WebServiceTEO6Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTEO6SoapClient : System.ServiceModel.ClientBase<ConsumirWebServiceTEO5.SR.WebServiceTEO6Soap>, ConsumirWebServiceTEO5.SR.WebServiceTEO6Soap {
        
        public WebServiceTEO6SoapClient() {
        }
        
        public WebServiceTEO6SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTEO6SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTEO6SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTEO6SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirWebServiceTEO5.SR.HelloWorldResponse ConsumirWebServiceTEO5.SR.WebServiceTEO6Soap.HelloWorld(ConsumirWebServiceTEO5.SR.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumirWebServiceTEO5.SR.HelloWorldRequest inValue = new ConsumirWebServiceTEO5.SR.HelloWorldRequest();
            inValue.Body = new ConsumirWebServiceTEO5.SR.HelloWorldRequestBody();
            ConsumirWebServiceTEO5.SR.HelloWorldResponse retVal = ((ConsumirWebServiceTEO5.SR.WebServiceTEO6Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirWebServiceTEO5.SR.HelloWorldResponse> ConsumirWebServiceTEO5.SR.WebServiceTEO6Soap.HelloWorldAsync(ConsumirWebServiceTEO5.SR.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirWebServiceTEO5.SR.HelloWorldResponse> HelloWorldAsync() {
            ConsumirWebServiceTEO5.SR.HelloWorldRequest inValue = new ConsumirWebServiceTEO5.SR.HelloWorldRequest();
            inValue.Body = new ConsumirWebServiceTEO5.SR.HelloWorldRequestBody();
            return ((ConsumirWebServiceTEO5.SR.WebServiceTEO6Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Sumar(int num1, int num2) {
            return base.Channel.Sumar(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> SumarAsync(int num1, int num2) {
            return base.Channel.SumarAsync(num1, num2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirWebServiceTEO5.SR.RegistrarClienteResponse ConsumirWebServiceTEO5.SR.WebServiceTEO6Soap.RegistrarCliente(ConsumirWebServiceTEO5.SR.RegistrarClienteRequest request) {
            return base.Channel.RegistrarCliente(request);
        }
        
        public ConsumirWebServiceTEO5.SR.Respuesta RegistrarCliente(ConsumirWebServiceTEO5.SR.Cliente cliente) {
            ConsumirWebServiceTEO5.SR.RegistrarClienteRequest inValue = new ConsumirWebServiceTEO5.SR.RegistrarClienteRequest();
            inValue.Body = new ConsumirWebServiceTEO5.SR.RegistrarClienteRequestBody();
            inValue.Body.cliente = cliente;
            ConsumirWebServiceTEO5.SR.RegistrarClienteResponse retVal = ((ConsumirWebServiceTEO5.SR.WebServiceTEO6Soap)(this)).RegistrarCliente(inValue);
            return retVal.Body.RegistrarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirWebServiceTEO5.SR.RegistrarClienteResponse> ConsumirWebServiceTEO5.SR.WebServiceTEO6Soap.RegistrarClienteAsync(ConsumirWebServiceTEO5.SR.RegistrarClienteRequest request) {
            return base.Channel.RegistrarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirWebServiceTEO5.SR.RegistrarClienteResponse> RegistrarClienteAsync(ConsumirWebServiceTEO5.SR.Cliente cliente) {
            ConsumirWebServiceTEO5.SR.RegistrarClienteRequest inValue = new ConsumirWebServiceTEO5.SR.RegistrarClienteRequest();
            inValue.Body = new ConsumirWebServiceTEO5.SR.RegistrarClienteRequestBody();
            inValue.Body.cliente = cliente;
            return ((ConsumirWebServiceTEO5.SR.WebServiceTEO6Soap)(this)).RegistrarClienteAsync(inValue);
        }
    }
}
